import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#ffe088',
        'surface-container': '#201f1f',
        'secondary-fixed': '#f7e1a6',
        'inverse-on-surface': '#313030',
        'surface': '#131313',
        'error': '#ffb4ab',
        'surface-container-lowest': '#0e0e0e',
        'primary-container': '#d4af37',
        'on-secondary-fixed-variant': '#544519',
        'inverse-primary': '#735c00',
        'tertiary': '#bfcdff',
        'outline': '#99907c',
        'on-surface': '#e5e2e1',
        'on-background': '#e5e2e1',
        'surface-bright': '#3a3939',
        'on-primary-fixed-variant': '#574500',
        'on-error-container': '#ffdad6',
        'tertiary-container': '#97b0ff',
        'secondary': '#dac58d',
        'primary-fixed-dim': '#e9c349',
        'on-primary-container': '#554300',
        'primary': '#f2ca50',
        'on-tertiary-fixed': '#00174b',
        'on-error': '#690005',
        'secondary-container': '#544519',
        'error-container': '#93000a',
        'on-tertiary': '#082b72',
        'secondary-fixed-dim': '#dac58d',
        'surface-variant': '#353534',
        'surface-dim': '#131313',
        'on-tertiary-container': '#254188',
        'outline-variant': '#4d4635',
        'on-secondary-fixed': '#241a00',
        'on-tertiary-fixed-variant': '#27438a',
        'on-secondary': '#3c2f05',
        'on-primary': '#3c2f00',
        'surface-tint': '#e9c349',
        'on-surface-variant': '#d0c5af',
        'on-primary-fixed': '#241a00',
        'tertiary-fixed-dim': '#b4c5ff',
        'surface-container-high': '#2a2a2a',
        'surface-container-low': '#1c1b1b',
        'inverse-surface': '#e5e2e1',
        'background': '#131313',
        'surface-container-highest': '#353534',
        'on-secondary-container': '#c8b37d',
        'tertiary-fixed': '#dbe1ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Noto Serif KR', 'serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
